### ISSUE TITLE
Not compatible with FF 7.0.1

### ISSUE THREAD

**Issue by walker** [cadorn/legacy-fireconsole#12]
Firefox realease update channel is currently at 7.0.1 and says that FireConsole is not compatible.

I tries installing pinf so I could fix this plugin, but pinf does not install based on the instructions for the Mac OS X command line. Sorry.

**Comment by cadorn** [comment]
I have updated the README for this project.

Please see: https://github.com/cadorn/fireconsole

The PINF platform mentioned in this project is the version prior to the latest one and no longer supported. The new PINF platform stuff is located at https://github.com/pinf/ with the [PINF JavaScript Loader](https://github.com/pinf/loader-js) being the first sub-project that is supported publicly and ready for wider testing.

I apologize for the confusion.
