### ISSUE TITLE
no console output

### ISSUE THREAD

**Issue by igor47** [cadorn/legacy-fireconsole#4]
although my server is returning the firephp headers, i get no messages in the console. In the Net panel, i can see the headers:
X-Wf-Protocol-1 http://meta.wildfirehq.org/Protocol/JsonStream/0.2
X-Wf-1-Plugin-1 http://meta.firephp.org/Wildfire/Plugin/FirePHP/Library-FirePHPCore/0.3
X-Wf-1-Structure-1  http://meta.firephp.org/Wildfire/Structure/FirePHP/FirebugConsole/0.1
X-Wf-1-1-1-1    96|[{"Type":"LOG","File":"\/home\/managetest\/lib\/class\/Base.class.php","Line":73},"field is ''"]|

I'm using: Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.7) Gecko/20100106 Ubuntu/9.04 (jaunty) Shiretoko/3.5.7
Firebug v. 1.4.5
I've disabled normal FirePHP using the extension manager when I installed FireConsole (0.0.0master1002082041)

**Comment by igor47** [comment]
my bad - i see that fireconsole requires firebug 1.5. 

Installing this forced me to upgrade to firefox 3.6 because of the 64-bit firefox-firebug incompatibility. now that i'm using firefox 3.6 and firebug 1.5 the console works again.

**Comment by cadorn** [comment]
I am tracking known issues here now: http://groups.google.com/group/fireconsole/web/known-issues

Closing ticket.
