### ISSUE TITLE
firephp.org site does not recognize that browser is using Firebug 1.5

### ISSUE THREAD

**Issue by yuvilio** [cadorn/legacy-fireconsole#6]
I'm on Ubuntu Karmic with firebug 1.5.0 and still see that red bar on top saying: "You need Firebug 1.5 which you can get from here."

**Comment by yuvilio** [comment]
using Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2) Gecko/20100123 Ubuntu/9.10 (karmic) Firefox/3.6

**Comment by cadorn** [comment]
fixed
